export const FETCH_EMPLOYEE_DATA = 'FETCH_EMPLOYEE_DATA';
export const SEARCH_EMPLOYEE = 'SEARCH_EMPLOYEE';
export const SHOW_DETAIL_EMPLOYEE = 'SHOW_DETAIL_EMPLOYEE';
export const ADD_EMPLOYEE_DATA = 'ADD_EMPLOYEE_DATA';
export const UPDATE_EMPLOYEE_DATA = 'UPDATE_EMPLOYEE_DATA';
