module.exports = {
  dashboard: '/app',
  login: '/login',
  register: '/register',
  resetPassword: '/reset-password',
  market: '#',
  email: '/app/pages/email',
  profile: '/app/my-profile',
  calendar: '/app/pages/calendar',
  twitter: '#',
  github: '#',
  pinterest: '#',
  linkedin: '#',
  buy: '#',
};
