export const FETCH_TODO_LIST = 'FETCH_TODO_LIST';
export const FETCH_TODO_DATA = 'FETCH_TODO_DATA';
export const SEARCH_TODO = 'SEARCH_TODO';
export const SHOW_DETAIL_TODO = 'SHOW_DETAIL_TODO';
export const ADD_TODO_DATA = 'ADD_TODO_DATA';
export const UPDATE_TODO_DATA = 'UPDATE_TODO_DATA';
